# Generated by Django 3.2.18 on 2023-08-10 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=70)),
                ('trans', models.CharField(max_length=70)),
                ('rus', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind', models.SmallIntegerField(default=0)),
                ('title', models.CharField(max_length=70)),
                ('text1', models.TextField()),
                ('content', models.TextField()),
                ('picture1', models.ImageField(blank=True, default='default/im.jpg', null=True, upload_to='images')),
                ('picture2', models.ImageField(blank=True, default='default/im.jpg', null=True, upload_to='images')),
                ('picture3', models.ImageField(blank=True, default='default/im.jpg', null=True, upload_to='images')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('upgrated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.CharField(max_length=5000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('user1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind', models.SmallIntegerField(default=0)),
                ('author', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=70)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bks/list', verbose_name='Основное изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Replie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.CharField(max_length=5000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.post')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default/user1.png', null=True, upload_to='images')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('content', models.CharField(max_length=150)),
                ('publication', models.SmallIntegerField()),
                ('num', models.SmallIntegerField()),
                ('authors', models.ManyToManyField(to='books.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Artc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind', models.SmallIntegerField(default=0)),
                ('title', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='bks/list', verbose_name='Основное изображение')),
                ('views', models.ManyToManyField(blank=True, related_name='artc_views', to='books.Ip')),
            ],
        ),
    ]
