# Generated by Django 3.2.18 on 2023-08-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist',
            name='picture1',
            field=models.ImageField(blank=True, default='default/im11.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='picture2',
            field=models.ImageField(blank=True, default='default/im11.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='picture3',
            field=models.ImageField(blank=True, default='default/im11.jpg', null=True, upload_to='images'),
        ),
    ]
