# Generated by Django 3.2.18 on 2023-08-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20230811_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artc',
            name='image',
        ),
        migrations.AddField(
            model_name='artc',
            name='capt1',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='artc',
            name='capt2',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='artc',
            name='capt3',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='artc',
            name='capt4',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='artc',
            name='capt5',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='artc',
            name='capt6',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='artc',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images/artc'),
        ),
        migrations.AddField(
            model_name='artc',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images/artc'),
        ),
        migrations.AddField(
            model_name='artc',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/artc'),
        ),
        migrations.AddField(
            model_name='artc',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='images/artc'),
        ),
        migrations.AddField(
            model_name='artc',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='images/artc'),
        ),
        migrations.AddField(
            model_name='artc',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='images/artc'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='text1',
            field=models.TextField(blank=True),
        ),
    ]
