# Generated by Django 3.2.18 on 2023-08-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20230813_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='hist',
            name='views',
            field=models.ManyToManyField(blank=True, default=0, related_name='hist_views', to='books.Ip'),
        ),
    ]
