# Generated by Django 3.2.18 on 2023-08-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_hist_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='pros',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='prse_views', to='books.Ip'),
        ),
    ]
